Fix current status (issue #100)
poncateam/ponca pull request #108
Opened 2023-08-04 10:48 UTC by ThibaultLejemble

This PR mainly fixes issue #100
It also improves
- the doc on `FIT_RESULT`
- the primitive base finalize
- the check on conflict

I have just a few questions or remarks
- the number of neighbors used to determine if a fit is stable or not should depends on the dimension right? For example, a PCA in 2D is stable with 2 neighbors, in 3D with 3 neighbors, etc... I wanted to be sure if it is correct for every fitting procedure and if it is pertinent to add this
- note that fitting an oriented sphere to 1 point and 1 normal vector in any dimension is always stable as it simply returns the plane that passes by this point with a normal equal to the normal of the input point. For 2 points in 2D I believe it is also quite stable in general. That being said, I am not sure for 2 points in 3D, the sphere fit may be good but the derivatives, the GLS, etc, may not be as good, and the stability may depends on the weighting function that is used, so it is safe to keep these thresholds in the end
- the file `linePrimitive.h` has the `Primive` kew-work in its title, whereas other primitives do not have it. For consistency, should we add it to the plane and algebraic sphere file name, or should we remove it from the line file name?

2023-08-04 12:41 UTC, nmellado approved these changes

2023-08-04 12:45 UTC, nmellado commented
> the number of neighbors used to determine if a fit is stable or not should depends on the dimension right? For example, a PCA in 2D is stable with 2 neighbors, in 3D with 3 neighbors, etc... I wanted to be sure if it is correct for every fitting procedure and if it is pertinent to add this

Right, good point. `Dim` is a good threshold.

> note that fitting an oriented sphere to 1 point and 1 normal vector in any dimension is always stable as it simply returns the plane that passes by this point with a normal equal to the normal of the input point. For 2 points in 2D I believe it is also quite stable in general. That being said, I am not sure for 2 points in 3D, the sphere fit may be good but the derivatives, the GLS, etc, may not be as good, and the stability may depends on the weighting function that is used, so it is safe to keep these thresholds in the end

The derivative class (or any other extension) can have a different instability threshold than the main class.

> the file linePrimitive.h has the Primive kew-work in its title, whereas other primitives do not have it. For consistency, should we add it to the plane and algebraic sphere file name, or should we remove it from the line file name?

Yes, right. Another option would be to have Primitive directory, and remove "primitive" in the file name. We could also add a Fit directory, and other files at the root. It would make the code structure more obvious, what do you think ?

2023-08-04 14:30 UTC, ThibaultLejemble commented
I will use `Dim` for the neighborhood thresholds that are currently used.
Good idea for the folders `Fit` and `Primitive`, should I add this in this PR, or in another one?

2023-08-04 14:40 UTC, ThibaultLejemble commented
For all the sphere fit, the status is `UNDEFINED` with less than `3` neighbors, and `UNSTABLE` with less than `6`.
Do you know why the `6` threshold? 
For now I replaced the `3` by `Dim`, and the `6` by `2*Dim`

2023-10-03 12:16 UTC, nmellado commented
@ThibaultLejemble could you please fix the naming issue that makes the tests failing (with `Dim`) ?

> Good idea for the folders Fit and Primitive, should I add this in this PR, or in another one ?

Can be in another one.

2023-10-03 13:22 UTC, nmellado requested changes
Seems to be ready for merging (after `Dim` fix).
Please rebase on top of `master`

2023-10-04 10:32 UTC, nmellado approved these changes

2023-10-04 10:33 UTC, merged