add mean plane
poncateam/ponca pull request #79
Opened 2023-05-25 02:01 UTC by jmaleo

Feature adding the base conversion from plane created from oriented point clouds.

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.h
> +class MeanPlane : public T
```suggestion
class LocalFrame : public T
```

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.h
> +        check = Base::PROVIDES_MEAN_POSITION && Base::PROVIDES_MEAN_NORMAL && Base::PROVIDES_PLANE,  /*!< \brief Requires PrimitiveBase */
```suggestion
        check = Base::PROVIDES_PLANE,  /*!< \brief Requires PrimitiveBase */
```

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.h
> +    MatrixType B; // local frame
Store only the missing vectors, to avoid redundancy with `Plane`

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.h
> +} // namespace Ponca
Add line at the end of the file (same for other files)

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.hpp
> +}
Add line at the end of the file

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.h
> +        PROVIDES_MEAN_PLANE_BASIS                                       /*!< \brief Provides Algebraic Sphere */
```suggestion
        PROVIDES_LOCAL_FRAME                                       /*!< \brief Provides TangentialFrame */
```

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.h
> +
Add a brief documentation of the class, explain requirements

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.h
> +    PONCA_EXPLICIT_CAST_OPERATORS(MeanPlane,meanPlane)
```suggestion
    PONCA_EXPLICIT_CAST_OPERATORS(LocalFrame,localFrame)
```

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.h
> +    PONCA_MULTIARCH inline VectorType worldToTangentPlane(const VectorType &_q) const;
```suggestion
    PONCA_MULTIARCH inline VectorType worldToLocalFrame(const VectorType &_q) const;
```

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.h
> +    PONCA_MULTIARCH inline VectorType tangentPlaneToWorld(const VectorType &_q) const;
```suggestion
    PONCA_MULTIARCH inline VectorType localFrameToWorld(const VectorType &_q) const;
```

2023-05-31 07:56 UTC, nmellado commented on Ponca/src/Fitting/meanPlaneFit.h
> +                    Plane<DataPoint, _WFunctor,T>>>>>;
```suggestion
        MeanNormal<DataPoint, _WFunctor,
            MeanPosition<DataPoint, _WFunctor,
                TangentPlane<DataPoint, _WFunctor,
                    Plane<DataPoint, _WFunctor,T>>>>>;
```

2023-05-31 16:42 UTC, nmellado commented on Ponca/src/Fitting/meanPlane.h
> +class MeanPlane : public T
I changed the suggested name to `PlaneFrame`

2023-06-09 15:35 UTC, nmellado commented
@jmaleo please fix compilation errors

2023-06-19 12:23 UTC, nmellado commented
Thanks, looks nice.

One last remark: could you set `m _u` and `m_v` as private, and add a protected setter (e.g. `setFrameUV(vector u, vector v)`, with the documentation explaining how the frame is constructed), and a public getter to each field (e.g., `getFrameU()` and `getFrameV()`).

2025-10-16 13:16 UTC, nmellado requested changes
@jmaleo please update according to master, and move frame estimator to dedicated Estimator class

2025-10-17 14:23 UTC, Me-k-01 reviewed
Nice work. We still have some warnings with Codacy about the includes you added. Not entirely sure why...

2025-10-17 14:23 UTC, Me-k-01 commented on Ponca/src/Fitting/localFrameEstimation.h
> +#include PONCA_MULTIARCH_INCLUDE_STD(limits)
Remove unused cmath and limits include
```suggestion
```

2025-10-17 14:23 UTC, Me-k-01 commented on tests/src/basket.cpp
> +#include <Ponca/src/Fitting/covarianceFit.h>
Here `localFrame.h`, `plane.h`, `covarianceFit.h` and `mean.h` are already imported in `covariancePlaneFit.h` which seems to make codacy mad for some reason. 

Is there a way to fix this @nmellado ?

2025-10-17 14:23 UTC, Me-k-01 commented on Ponca/src/Fitting/localFrame.h
> +#include PONCA_MULTIARCH_INCLUDE_STD(limits)
Remove unused include

```suggestion
```

2025-10-17 14:23 UTC, Me-k-01 commented on tests/src/fit_monge_patch.cpp
>  #include <Ponca/src/Fitting/meanPlaneFit.h>
See previous comment about the include duplication of `covariancePlaneFit.h`, which makes Codacy unhappy.

2025-10-17 14:23 UTC, Me-k-01 commented on tests/src/fit_plane.cpp
> +#include <Ponca/src/Fitting/covarianceFit.h>
See previous comment about the include duplication of `covariancePlaneFit.h`, which makes Codacy unhappy.

2025-10-17 14:23 UTC, Me-k-01 commented on tests/src/dnormal_orthogonal_derivatives.cpp
> +#include <Ponca/src/Fitting/covarianceFit.h>
See previous comment about the include duplication of `covariancePlaneFit.h`, which makes Codacy unhappy.

2025-10-17 14:23 UTC, Me-k-01 commented on Ponca/src/Fitting/localFrame.hpp
> +}
Just like what was [suggested from @nmellado](https://github.com/poncateam/ponca/pull/177#discussion_r2435961493)  that was made on PR #177 Here we could make an intermediary function that takes in a point in local basis and does the computation. Basically we could have : 
- [ ] A **protected** `localToLocalFrame (const VectorType& _lq)` that is only accessible from inside the CRTP and takes in a local coordinate to do the matrix computation.
- [ ] A **public** `worldToLocalFrame (const VectorType& _q)` that takes in a point in world space, do the `Base::m_w.convertToLocalBasis(_q)` and calls `localToLocalFrame(_lq)` to finish the computation.

2025-10-30 19:21 UTC, nmellado commented
#177  PR has been merged, so this proposal can be updated accordingly.

2025-11-24 14:23 UTC, Me-k-01 submitted a review, later dismissed

2025-12-10 14:29 UTC, Me-k-01 commented
Ready for review @nmellado

2026-01-26 15:29 UTC, nmellado commented
Let's wait after we merged #195

2026-03-30 10:38 UTC, Me-k-01 commented
This PR needs to be cleanly rebased and updated with master

2026-03-31 09:19 UTC, Me-k-01 commented
Needs to wait for after the Fitting PR that will better separate the **Computational structures** from the **Data owning structures.**

2026-05-28 15:32 UTC, nmellado commented
Handled by concepts

2026-05-28 15:32 UTC, closed without merging